// packages/reactxy/src/components/input/input.tsx
/*
 * @Author: Chengbotao
 * @Date: 2022-11-19 23:46:16
 */
import React, { ChangeEvent, FC, InputHTMLAttributes, ReactElement } from 'react';
import { IconProp } from '@fortawesome/fontawesome-svg-core';
import classNames from 'classnames';
import Icon from '../icon/icon';

export type InputSize = 'lg' | 'sm';

export interface InputProps extends InputHTMLAttributes<HTMLElement> {
  /** 设置 Input 禁用 */
  disabled?: boolean;
  /** 设置 Input 尺寸 */
  sized?: InputSize;
  /** 添加图标,在右侧悬浮添加一个图标，用于提示 */
  icon?: IconProp;
  /** 添加前缀 用于配置一些固定组合 */
  prepend?: string | ReactElement;
  /** 添加后缀 用于配置一些固定组合 */
  append?: string | ReactElement;
  /** 自定义 css 类名 */
  className?: string;
  onChange?: (e: ChangeEvent<HTMLInputElement>) => void;
}

/**
 * Input 组件
 *
 */
export const Input: FC<InputProps> = (props) => {
  const { disabled, sized, icon, prepend, append, className, ...restProps } = props;
  const classes = classNames('xy-input-wrapper', className, {
    [`xy-input-size-${sized}`]: sized,
    'is-disabled': disabled,
    'xy-input-group': prepend || append,
    'xy-input-group-append': !!append,
    'xy-input-group-prepend': !!prepend,
  });

  // 受控组件 || 非受控组件
  const fixControlledValue = (value: any) => {
    if (typeof value === 'undefined' || value === null) {
      return '';
    }
    return value;
  };
  if ('value' in props) {
    delete restProps.defaultValue;
    restProps.value = fixControlledValue(props.value);
  }

  return (
    <div className={classes} style={props.style}>
      {prepend && <div className="xy-input-group-prepend">{prepend}</div>}
      {icon && (
        <div className="icon-wrapper">
          <Icon icon={icon} title={`title-${icon}`} />
        </div>
      )}
      <input className="xy-input-inner" disabled={disabled} {...restProps} />
      {append && <div className="xy-input-group-append">{append}</div>}
    </div>
  );
};

export default Input;

// packages/vue3xy/src/components/input/input.vue
<!--
 * @Author: Chengbotao
 * @Date: 2022-11-19 23:47:15
-->
<template>
    <div :class="classes">
        <div v-if="slots.prepend" key="prepend" class="xy-input-group-prepend">
            <slot name="prepend"></slot>
        </div>
        <div v-if="icon" key="icon" class="icon-wrapper">
            <xyIcon :icon="icon"></xyIcon>
        </div>
        <input class="xy-input-inner" v-bind="$attrs" :disabled=disabled @focus="handleFocus" @blur="handleBlur"
            @change="handleChange" @input="handleInput" :value="modelValue" />
        <div v-if="slots.append" key="append" class="xy-input-group-append">
            <slot name="append"></slot>
        </div>
    </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
    name: 'XyInput',
    inheritAttrs: false,
})
</script>

<script setup lang="ts">
import { useSlots } from "vue";
import { IconProp } from '@fortawesome/fontawesome-svg-core';
import classNames from 'classnames';

type InputSize = 'lg' | 'sm';

interface InputProps {
    modelValue?: string | number;
    disabled?: boolean;
    sized?: InputSize;
    icon?: IconProp;
    className?: string;
}

interface InputEmits {
    (event: "input", payload: InputEvent): void
    (event: "focus", payload: FocusEvent): void
    (event: "blur", payload: FocusEvent): void
    (event: "change", payload: Event): void
    (event: "update:modelValue", payload: string): void
}
// slots
const slots = useSlots();

// Props
const props = withDefaults(defineProps<InputProps>(), {
    modelValue: ""
});

// Emits
const emits = defineEmits<InputEmits>();

// computed
const classes = classNames('xy-input-wrapper', props.className, {
    [`xy-input-size-${props.sized}`]: props.sized,
    'is-disabled': props.disabled,
    'xy-input-group': slots?.prepend || slots?.append,
    'xy-input-group-append': !!slots?.append,
    'xy-input-group-prepend': !!slots?.prepend,
});

// methods
const handleInput = (event: InputEvent) => {
    emits("input", event)
    emits("update:modelValue", (event.target as HTMLInputElement).value)
}
const handleFocus = (event: FocusEvent) => {
    emits("focus", event)
}
const handleBlur = (event: FocusEvent) => {
    emits("blur", event)
}
const handleChange = (event: Event) => {
    emits("change", event)
}

// public 方法
defineExpose({})
</script>
